				Last Updated: November 20, 2015<br><br>
				Welcome to <a href="/">expertsolarhelp.com</a>, a Web site ("Site") of C2C Marketing, Inc. ("we" or "us").<br><br>
				We respect the privacy of those who access and/or use the Site ("you", "your", "user" or collectively "users") and are committed to protecting the personally identifiable information we collect. Your personal information will be shared only with third-party vendor(s), installer(s) or service providers necessary to provide the information and service(s) that you yourself have requested.<br><br>
				1. CHANGES TO THIS POLICY<br>
				If this Privacy Policy changes, we will post all changes in an amended version with a new "Last Updated" date at the top of this Privacy Policy.<br><br>
				2. INFORMATION THAT WE COLLECT<br>
				We collect two types of information from you. The first type is personal information that you actively choose to disclose ("Active Information") and the second type is anonymous aggregate information collected in a manner not visible to you or others visiting the Site ("Passive Information").<br><br>
				a. <em>Active Information</em>. Examples of personally identifiable information that you provide to us may include your first and last name, mailing address, phone number, birthdate, email address, information about your finances including credit score, home ownership status, utility provider information, information about utility and other expenses, education and interests. In providing Active Information, you consent and agree to being contacted with information related to your specific inquiry as well as information about products and services generally relevant to home owners. If you provide personally identifiable information to us, you may later request to have that information deleted from our files, or kept from being used by us for purposes other than for the services requested, by following the opt-out procedures set forth below.<br><br>
				b. <em>Passive Information</em>. We record information relating to your use of the Site, such as the information you click on, your browser type, IP address, referring URL, and timestamp information. We use this type of information to administer the Site and provide the highest possible level of service to you. We may also use this information in the aggregate to perform statistical analyses of user behavior and characteristics in order to measure interest in and use of the various areas of the Site.<br><br>
				3. HOW COLLECTED INFORMATION IS USED<br>
				The Active and Passive Information we collect may be used by us in a variety of ways; to provide the information and services you request during registration at the Site, to keep you informed about industry developments, news, products, services, and opportunities generally of interest to home owners and for internal company purposes such as auditing, data analysis, research, information verification and anti-fraud activities.<br><br>
				4. USE OF COOKIES<br>
				We use cookies to store users' preferences and to record session information. To learn more about this practice please click here: <a target="_blank" href="http://www.networkadvertising.org/managing/opt_out.asp" rel="nofollow">http://www.networkadvertising.org/managing/opt_out.asp</a>. You may disable cookies by adjusting the settings on your Web browser. You may be able to configure your browser to accept or reject all or some cookies, or notify you when a cookie is set. Each browser is different, so you may wish to review the "Help" menu of your browser to learn how to change your cookie preferences. Note, however, that you may be required to enable cookies in order to use certain functions on our Site. We may use technology to verify the accuracy of data provided such as email address, physical address and phone numbers. We may also incorporate technologies used by advertising or analytical partners. Some such partners include, but are not limited to: (i) Google Analytics (used to track statistical information such as page visits and traffic source information allowing us to improve the performance and quality of the Site; to learn more about this please click here: <a target="_blank" href="http://www.google.com/analytics/learn/privacy.html" rel="nofollow">http://www.google.com/analytics/learn/privacy.html</a>), and (ii) Google Advertising (used to track conversions from advertisements on the Google Search and Google Display Network; to learn more about this please click here: <a target="_blank" href="http://www.google.com/policies/technologies/ads/" rel="nofollow">http://www.google.com/policies/technologies/ads/</a>). Third party pixels and content may also make use of cookies. We do not have access to or control over these third party cookies and this Privacy Policy does not cover the use of third party cookies.<br><br>
				5. DO-NOT-TRACK POLICY<br>
				We honor "do-not-track" signals and therefore do not track individuals' online activities over time and across third party sites.<br><br>
				6. INFORMATION SHARING AND DISCLOSURE<br>
				We do not share, license, or sell information we collect to third parties except as required in order to provide the information and services you request during registration at the Site.<br><br>
				From time to time, we may create, purchase or sell business subsidiaries. We may disclose your personal information to any subsidiary we create or purchase for the purpose of delivering the information and services which you request during registration. In addition, personal information constitutes a business asset that is transferable in any sales transaction involving business subsidiaries. Whether C2C Marketing Inc. creates, acquires or sells a business subsidiary, any personal information that is shared or sold will remain subject to the terms of the privacy policy then current, unless users subsequently consent otherwise.<br><br>
				Additionally, as a condition to registration at the Site, you explicitly agree to RECEIVE TELEPHONE CALLS FROM VENDORS AND INSTALLERS THAT MAY DELIVER AUTODIALED AND/OR PRERECORDED TELEMARKETING MESSAGES INCLUDING APPOINTMENT SETTING AND CONFIRMATION OF YOUR REQUEST FOR QUOTATION ON BEHALF OF IDENTIFIED THIRD PARTY SERVICE PROVIDERS.<br><br>
				We also reserve the unequivocal right to release all of your information, to the maximum extent permitted by law in the event that: (i) we believe that the Site is being or has been used to commit unlawful acts, (ii) the information is subpoenaed or otherwise required in a court proceeding, (iii) you violate or breach an agreement with the Site, (iv) you have submitted fraudulent or otherwise invalid information to this Site, (v) we believe that you may harm, or have harmed, the property or other rights of us, our employees, the Site's other users or any other third party, (vi) we are sold to or otherwise acquired by any individual, entity or organization (i.e. to a successor entity in the event of sale of the business, including merger, bankruptcy or other ownership change), or (vii) when we otherwise deem it necessary or appropriate. We may disclose any record or communication to any third party when we, in our sole discretion, determine the disclosure to be appropriate including, without limitation, sharing your email address with other third parties for suppression purposes in compliance with the requirements of the CAN-SPAM Act of 2003, as amended from time to time, or any other applicable state or federal law, rule or regulation.<br><br>
				7. OPTING-OUT<br>
				We may use your personal information to send you notices regarding changes to our Terms of Use, this privacy policy, and other policies relating to the site. You may not opt out of receiving these communications when you become a registered user.<br><br>
				If you no longer wish to receive promotional communications from us, you may opt-out by following the instructions included in each promotional communication or by returning to the Site and clicking on the Unsubscribe link provider at the bottom of the home page of the Site, or by contacting us as provided in this Privacy Policy. You may continue to receive promotional email communications from us for up to 10 business days from the time we receive your unsubscribe request.<br><br>
				Please note that we can only control our own mailing list, email list, phone number list, text message practices, and policies. We are not responsible for third party service provider communications and advertising practices. You must contact third parties directly in order to stop receiving communications from them.<br><br>
				8. ACCESS/ACCURACY<br>
				To the extent that you do provide us with certain personally identifiable information, we strive to maintain the accuracy of this information. Our goal is to provide a means to contact us should you need to review, update or correct your information. If for any reason those means are unavailable or inaccessible through the Site, you may send your request to review, update or correct your personally identifiable information to <a href="mailto:legal@expertsolarhelp.com">legal@expertsolarhelp.com</a> and we will make reasonable efforts to comply as soon as possible. You must send your request from the email address you provided at the time of registration so we can uniquely identify you. All such requests are subject to execution of a release form that will be provided to you for this purpose.<br><br>
				9. SECURITY OF INFORMATION<br>
				Use of the Site is at your own risk. We do, however, make reasonable efforts to secure your information, including, but not limited to, monitoring our network and data for intrusions. We also use industry-accepted standards to protect your information, including SSL encryption if transmitting sensitive information. Communications you may have with us via email or mail may not be secure unless we advise you that security measures are in place prior to your sending information.<br><br>
				10. LINKS TO THIRD PARTY SITES<br>
				The Site may contain links to third party sites including sites with which we have no affiliation. We are not responsible for their privacy practices. It is recommended you read the privacy policies on all such third party sites.<br><br>
				11. CALIFORNIA PRIVACY RIGHTS<br>
				Under California's "Shine the Light" law, California residents are entitled to either: (i) a list detailing the categories of information shared with third parties for direct marketing purposes and the entities to which such information was provided, or (ii) be notified of a mechanism by which a consumer may opt-out of having their information shared with third parties for direct marketing purposes. We have elected the second option. To opt-out of having your information shared with third parties for direct marketing purposes going forward, simply email us at <a href="mailto:optout.shine@expertsolarhelp.com">optout.shine@expertsolarhelp.com</a> with the words "Opt-Out" in the subject header.<br><br>
				12. NO USERS UNDER 18; COPPA<br>
				If you are under 18, you may not access or use the Site. BY ACCESSING OR USING THE SITE, YOU REPRESENT THAT YOU ARE AT LEAST 18 YEARS OLD. In compliance with COPPA, we do not knowingly collect personally identifiable information from users under 13.<br><br>
				13. NO INTERNATIONAL USERS<br>
				THE SITE AND SERVICES ARE NOT OFFERED FOR USE BY PERSONS RESIDING IN JURISDICTIONS OTHER THAN THE CONTINENTAL U.S. AND ALASKA AND HAWAII. If you live in any location other than the 50 states comprising the United States of America, you may not use the Site.<br><br>
				14. CONSENT TO INTERNATIONAL TRANSFER<br>
				Information we collect may be transferred, stored or processed in any country that we or our affiliates, subsidiaries, third party service providers or agents maintain facilities. By using the Site or Services you consent to any such transfer, storage and processing of information.<br><br>
				15. CONTACT INFORMATION<br>
				For more information, or if you have questions or concerns regarding our Privacy Policy or wish to opt-out as provided above, you may email us at <a href="mailto:legal@expertsolarhelp.com">legal@expertsolarhelp.com</a> or send us correspondence at the following address:<br><br>
				ATTN: ExpertSolarHelp.com<br>
				C/O C2C Marketing Inc.<br>
				2657 Windmill Pkwy<br>
				Suite 265<br>
				Henderson, NV 89074<br>
