				Last Updated: November 20, 2015<br><br>
				Welcome to <a href="/">expertsolarhelp.com</a>, a Web site ("Site") of C2C Marketing, Inc. ("we" or "us").<br><br>
				This agreement ("Agreement") is made between us and you ("you" or "user") (jointly the "parties" and each individually a "party") and sets forth the terms of use that apply to your access to and use of the Site.<br><br>
				1. ACCEPTANCE &amp; CHANGES<br>
				By visiting or accessing the Site, you agree to be bound by this Agreement. You also represent that you have not been previously suspended from using the Site. You further consent to the terms of our online Privacy Policy and to our use and processing of any user information for the purposes provided in the Privacy Policy.<br><br>
				<em>Your visitation and/or use of the Site mean that you accept this Agreement and the practices set forth in our Privacy Policy. We reserve the right to make changes to this Agreement and/or our Privacy Policy at any time. Any change will become effective no sooner than 14 days after it is posted, unless the change relates to the functionality of a new service or a change in the law, in which case the change will be effective immediately. Your continued use following any effective change indicates your agreement and/or consent to the change(s). It is your sole responsibility to check back regularly for updates to this Agreement and our Privacy Policy.</em><br><br>
				IF YOU DO NOT AGREE WITH ANY OF THESE TERMS, YOU MUST STOP USING THE SITE IMMEDIATELY.<br><br>
				2. WHAT WE DO<br>
				We provide information about products, services and opportunities available to home owners including but not limited to solar energy, home warranty, home security, home automation, home insurance, home mortgage and refinance, remodeling and contractor services and upon registration we facilitate the receipt of services and quotations from third party providers ("Third Party Service Providers"). To submit a request for more information, opportunities, products, and services, you must complete the registration that we make available on the Site. Once you submit the registration, we may direct you to the Site of the applicable Third Party Service Provider. You may be required to complete additional registration forms requested by the Third Party Service Provider.<br><br>
				3. WHAT WE DO NOT DO<br>
				We are not a financial institution, financial services provider, lender, insurance provider, insurance broker, real estate broker, your agent, or an agent of any state government or of the federal government. We do not offer financial or investment advice, insurance advice, real estate advice, medical or legal advice. Content, advertising, sponsorships, promotions and other information made available on the Site are provided for your reference only. We are not a party to any agreement you may enter into with a Third Party Service Provider, and we have no control over whether or not an application submitted to a Third Party Service Provider is approved, or whether or not you qualify for such program. The terms and conditions of any program provided by a Third Party Service Provider are determined solely by that Third Party Service Provider, not us.<br><br>
				4. REGISTRATION, TERMINATION AND CANCELLATION<br>
				You must provide us with complete, accurate and true information. We may reject an application or terminate the registration of any user at any time for any reason in our sole discretion. You may cancel your registration at any time by sending an e-mail with the subject line "CANCELLATION" to <a href="mailto:legal@expertsolarhelp.com">legal@expertsolarhelp.com</a>. You must send your request from the email address you provided at the time of registration so we can uniquely identify you. Thereafter, you will no longer receive communications from us. If you wish to unsubscribe from any future third party communications for which you have registered, you must unsubscribe from them directly.<br><br>
				5. NO RELIANCE ON INFORMATION<br>
				We make reasonable efforts to provide interesting, helpful and accurate information on the Site. Nonetheless, you should not rely on the accuracy or completeness of any information we provide. You should seek legal and industry expert counsel before taking any action as a result of information available on the Site.<br><br>
				6. COMPLIANCE<br>
				You agree that by prominently posting our Terms of Use and Privacy Policy on the Site, and by providing hyperlinks to the Terms of Use and Privacy Policy in any communication that we send, that we have fulfilled all requirements, if any, to provide notice to you that may be required by state and federal rules, regulations, and acts pertaining to the collection and use of consumer data, including but not limited to the CAN-SPAM Act, the Gramm Leach Bliley Act, the FTC Privacy Report and its rules and regulations, and the Fair Credit Reporting Act.<br><br>
				7. CONSENT<br>
				By registering on the Site, you give us and Third Party Service Providers unambiguous prior express written consent to contact you by email, telephone, and text message at the email address and telephone number you designate. You also agree that the act of registering on the Site constitutes a purchase, an inquiry and/or an application for purposes of the Amended Telemarketing Sales Rule, 16 C.F.R. &sect; 310 et seq. ("ATSR"). Once you register, and notwithstanding that your telephone number may be listed on the Federal Trade Commission's Do-Not-Call List, or a state do-not-call list, you agree that you have authorized us to contact you as described above in this paragraph in accordance with the ATSR. If you provide your express consent, YOU MAY RECEIVE FUTURE CALLS THAT DELIVER AUTODIALED AND/OR PRERECORDED TELEMARKETING MESSAGES ON OUR BEHALF. We do not charge a fee to register with or use the Site. If you no longer wish to receive communications from us, you must follow the opt-out procedures contained in our Privacy Policy.<br><br>
				Further, by registering with, or requesting information from, a Third Party Service Provider that may be made available through the Site or other feature we make available (e.g., email marketing), you agree that such action shall constitute a purchase, an inquiry and/or an application with the respective Third Party Service Provider for purposes of the ATSR and that you will be contacted as described in the above paragraph by such Third Party Service Providers in accordance with the ATSR. If you provide your express consent, YOU MAY RECEIVE FUTURE CALLS THAT DELIVER AUTODIALED AND/OR PRERECORDED TELEMARKETING MESSAGES ON BEHALF OF THIRD PARTY SERVICE PROVIDERS. If you no longer wish to receive communications from a Third Party Service Provider, you must follow its opt-out procedure.<br><br>
				8. NO USERS UNDER 18; COPPA<br>
				If you are under 18, you may not access or use the Site. BY ACCESSING OR USING THE SITE, YOU REPRESENT THAT YOU ARE AT LEAST 18 YEARS OLD. In compliance with COPPA, we do not knowingly collect personally identifiable information from users under 13.<br><br>
				9. NO INTERNATIONAL USERS<br>
				THE SITE IS NOT OFFERED FOR USE BY PERSONS RESIDING IN JURISDICTIONS OTHER THAN THE CONTINENTAL U.S. AND ALASKA AND HAWAII. If you live in any location other than the 50 states comprising the United States of America, you may not use the Site.<br><br>
				10. TERMINATION OF AGREEMENT<br>
				This Agreement may be terminated by us in the event that you breach any of your duties, obligations or responsibilities under the Agreement. Upon or following termination, we shall have no liability to you or any further obligations under this Agreement.<br><br>
				11. OUR CONTENT AND TECHNOLOGY<br>
				"Our Content" means any intellectual property, data, or communications transmitted by us, our users or third-parties via our platforms ("Platforms") including, but not limited to files, images, listings, logos, messages, postings, ratings, recommendations, reviews, text, trademarks or editorial content. It also includes all content generated by us.<br><br>
				"Our Technology" means any past, present and future intellectual property or related rights in the Platforms, including, but not limited to, software, code processes, algorithms, user interfaces, know-how, techniques, organization, designs, text, images, photographs, illustrations, artwork, graphic material, advertising copy, databases, proprietary information, all copyrightable or otherwise legally protectable elements of the Platforms and all other tangible or intangible materials related to, displayed, performed, or distributed on the Platforms and the Platforms themselves, including, but not limited to the selection, sequence, "look and feel" and arrangement of items on the Platforms, and all of our marks, domain names, patents and other intellectual property.<br><br>
				Unless otherwise noted, all of Our Content is owned, controlled or licensed by us. Our Content is protected by copyright, trademark, service mark, and/or other intellectual property rights. You understand and agree that you shall acquire no rights in Our Content or Our Technology unless otherwise stated in writing.<br><br>
				a. <em>License to Access and/or Use</em>. We grant you a limited, personal, non-exclusive, non-transferable, freely revocable license to access and/or use Our Content and Our Technology to use the Site. You agree and understand that with the exception of this limited license, you have no rights in or to Our Content or Our Technology unless otherwise stated in writing. This limited license terminates automatically and without notice to you if you breach this Agreement.<br><br>
				b. <em>Reservation of Rights</em>. We reserve all rights not expressly granted in this Agreement unless otherwise stated in writing.<br><br>
				c. <em>Prevention of Unauthorized Use</em>. We reserve the right to employ whatever lawful means we consider necessary to prevent unauthorized use of the Site, Our Content and/or Our Technology, including, but not limited to, technological barriers, IP mapping and contacting your Internet Service Provider (ISP).<br><br>
				12. COPYRIGHT AND TRADEMARK INFRINGEMENT POLICY<br>
				<em>Notification</em>: If you believe in good faith that material hosted by the Site infringes your copyright or trademark, you or your agent may send us a written notice that includes the following information:<br><br>
				a. A clear identification of the copyrighted or trademarked work you claim was infringed;<br><br>
				b. A clear identification of the material you claim is infringing the copyrighted or trademarked work, and information that will allow us to locate that material on the Site, such as a link to the infringing material;<br><br>
				c. Your contact information so that we can reply to your complaint, preferably including an email address and telephone number;<br><br>
				d. A statement that you have a "good faith belief that the material that is claimed as copyright/trademark infringement is not authorized by the copyright/trademark owner, its agent, or the law";<br><br>
				e. A statement that "the information in the notification is accurate, and under penalty of perjury, the complaining party is authorized to act on behalf of the owner of an exclusive right that is allegedly infringed"; and<br><br>
				f. The notice must be signed by the person authorized to act on behalf of the owner of an exclusive right that is allegedly infringed.<br><br>
				Notices should be sent to the Notice address under the MISCELLANEOUS section below, Attn: Copyright and Trademark Agent. We will review and address all notices that comply with the requirements above. If we remove or disable access in response to such a notice, we may notify the owner or administrator of the affected site or content so that he or she can make a counter notification.<br><br>
				<em>Counter-notification</em>: If you believe in good faith your material that was removed or disabled was not infringing, or that you had authorization from the copyright/trademark owner or the copyright/trademark owner's agent, or pursuant to the law, to post and use the materials, you or your agent may send us a written notice that includes the following information:<br><br>
				a. Your physical or electronic signature;<br><br>
				b. Identification of the material that has been removed or to which access has been disabled and the location at which the material appeared before it was removed or access to it was disabled;<br><br>
				c. A statement under penalty of perjury that you have a good faith belief that the material was removed or disabled as a result of mistake or misidentification of the material to be removed or disabled; and<br><br>
				d. Your name, address and telephone number, and a statement that you consent to the jurisdiction of the federal court in Las Vegas, Nevada and that you will accept service of process from the person who provided notification of the alleged infringement or an agent of such person.<br><br>
				If counter-notice is received by us, we may send a copy to the complaining party stating that we may replace the material or cease disabling access in 10 business days unless an action is filed seeking a court order.<br><br>
				Notwithstanding the foregoing, we reserve the right to remove material deemed to be infringing, at our sole discretion, without prior notice and without liability to you. In appropriate circumstances, we will also terminate a user's account if we determine, at our sole discretion, that he or she is a repeat infringer.<br><br>
				13. PROHIBITIONS ON USE<br>
				You may not do or encourage any of the following actions on the Site:<br><br>
				a. Sell, resell, lease, sublicense, market, distribute, assign or otherwise transfer rights to or commercially exploit any portion of the Site;<br><br>
				b. Take any action that imposes an unreasonable or disproportionately large load on the Site's infrastructure;<br><br>
				c. "Scrape" the Site, or use any bot, spider, data miner or automated agent to access and/or use the Site or gain access to or use any of Our Content;<br><br>
				d. Reformat, copy, reproduce, modify, translate or create derivative works of or display any portion of the Site, or mirror and/or frame any pages of the Site on any other Web site;<br><br>
				e. Attempt to decipher, decompile, disassemble, or reverse engineer any of Our Technology;<br><br>
				f. Remove or interfere with any of Our Content, Our Technology or any other proprietary right of the Site; or<br><br>
				g. Use the Site: (i) for any unlawful purpose, (ii) to defraud or mislead us or any third-party, or (iii) to create damage or risk to us or any third-party business, network or facility.<br><br>
				14. PERSONAL USE ONLY<br>
				The Site is available only for users' personal non-business use. Any other use is prohibited, unless otherwise stated in writing to you by us.<br><br>
				15. THIRD-PARTY LINKS<br>
				The Site may provide links to other sites (each a "linked site") and allow you to leave the Site to access third-party material or bring third-party material to the site via "inverse" hyperlinks and framing technology. We have no discretion to alter, update, or control the content of a linked site. The fact that we have provided a link to a linked site is not an endorsement, authorization, sponsorship, or affiliation with respect to such linked site, its owners, or its providers. There are inherent risks in relying upon using, or retrieving any information found on the Internet, and we urge you to make sure you understand these risks before relying upon, using, or retrieving any such information on a linked site.<br><br>
				16. LINKING TO THE SITE<br>
				You may link to the Site, provided you do so in a manner that does not damage our reputation or encourage or endorse any use of the Site that would breach the Terms. However, you must not establish a link in such a way as to suggest any association, approval or endorsement by use where none exists.<br><br>
				17. NON-RELIANCE ON SITE<br>
				We may discontinue or change any of Our Content or any service, function, or feature of the Site at any time with or without notice.<br><br>
				18. DISCLAIMER OF WARRANTIES<br>
				a. YOU UNDERSTAND AND AGREE THAT WE DO NOT GUARANTEE THE ACCURACY, SUITABILITY OR COMPLETENESS OF ANY INFORMATION IN OR PROVIDED IN CONNECTION WITH THE SITE. WE ARE NOT RESPONSIBLE FOR ANY ERRORS OR OMISSIONS OR FOR THE RESULTS OBTAINED FROM THE USE OF SUCH INFORMATION.<br><br>
				b. WE EXPRESSLY DISCLAIM ANY AND ALL REPRESENTATIONS AND WARRANTIES OF ANY KIND OR NATURE, EXPRESS OR IMPLIED, INCLUDING REPRESENTATIONS AND WARRANTIES OF QUALITY, MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND THOSE ARISING BY STATUTE OR OTHERWISE IN LAW OR FROM A COURSE OF DEALING OR USE OF TRADE.<br><br>
				c. ANY ADVERTISERS, EQUIPMENT MANUFACTURERS, RESELLERS AND SERVICE PROVIDERS APPEARING ON OR THROUGH THE SITE ARE NOT OUR AGENTS OR EMPLOYEES AND WE ARE NOT LIABLE FOR THE ACTS, ERRORS, OMISSIONS, REPRESENTATIONS, WARRANTIES, BREACHES OR NEGLIGENCE OF ANY ENTITY OR SERVICE APPEARING ON OR AVAILABLE THROUGH THE SITE, INCLUDING BUT NOT LIMITED TO INJURIES, DEATH, PROPERTY DAMAGE OR OTHER DAMAGES OR EXPENSES RESULTING THEREFROM.<br><br>
				d. WE DO NOT REPRESENT OR WARRANT THAT: (i) THE SITE WILL MEET USERS' REQUIREMENTS OR EXPECTATIONS, (ii) THE SITE WILL BE ERROR-FREE OR UNINTERRUPTED OR THAT INFORMATION OBTAINED WILL BE ACCURATE OR RELIABLE, OR (iii) THAT ALL DEFICIENCIES IN THE SERVICE CAN BE FOUND OR CORRECTED. FURTHER, THE SITE MAY BE INTERRUPTED OR UNAVAILABLE FOR THE PURPOSES OF PERFORMING MAINTENANCE OR UPGRADES. WE WILL NOT BE RESPONSIBLE FOR: (1) SERVICE IMPAIRMENTS CAUSED BY ACTS WITHIN THE CONTROL OF USER OR ANY USER, (2) INTEROPERABILITY OF SPECIFIC USER APPLICATIONS OR EQUIPMENT, (3) INABILITY OF USERS TO ACCESS OR INTERACT WITH ANY OTHER SERVICE PROVIDER THROUGH THE INTERNET, OTHER NETWORKS OR USERS THAT COMPRISE THE INTERNET OR THE INFORMATIONAL OR COMPUTING RESOURCES AVAILABLE THROUGH THE INTERNET, (4) INTERACTION WITH OTHER SERVICE PROVIDERS, NETWORKS, USERS OR INFORMATIONAL OR COMPUTING RESOURCES THROUGH THE INTERNET, (5) SERVICE PROVIDED BY OTHER SERVICE PROVIDERS, OR (6) PERFORMANCE IMPAIRMENTS CAUSED ELSEWHERE ON THE INTERNET.<br><br>
				e. WE DO NOT WARRANT THAT THE SERVICE OR ITS OPERATION WILL BE ACCURATE, RELIABLE, UNINTERRUPTED, ERROR-FREE OR FREE OF VIRUSES OR OTHER HARMFUL AGENTS.<br><br>
				19. LIMITATION OF LIABILITY<br>
				a. IN NO EVENT, INCLUDING NEGLIGENCE, WILL WE OR ANYONE ELSE INVOLVED IN ADMINISTERING THE SITE BE LIABLE FOR ANY DIRECT, SPECIAL, INCIDENTAL, INDIRECT, OR CONSEQUENTIAL LOSS OR DAMAGE, LOSS OF DATA, DAMAGES FOR DELAY, PUNITIVE OR EXEMPLARY DAMAGES, OR ANY CLAIM AGAINST USER BY ANY OTHER PERSON RESULTING FROM MISTAKES, OMISSIONS, SERVICE INTERRUPTIONS, SERVER DOWNTIME, ERRORS, DEFECTS, VIRUSES, DELAYS IN OPERATION OR TRANSMISSION, OR FAILURE OF PERFORMANCE OF THE SERVICE, EVEN IF WE HAVE BEEN ADVISED OF THE POSSIBILITY OF ANY SUCH LOSSES OR DAMAGES.<br><br>
				b. WE SHALL NOT BE LIABLE FOR UNAUTHORIZED ACCESS TO OR ALTERATION, THEFT, LOSS OR DESTRUCTION OF ANY DATA, EQUIPMENT OR SERVICES, INCLUDING THROUGH ACCIDENT, FRAUDULENT MEANS OR DEVICES, OR ANY OTHER METHOD.<br><br>
				c. WE SHALL BE LIABLE TO USERS ONLY AS EXPRESSLY PROVIDED IN THIS AGREEMENT AND SHALL HAVE NO OTHER OBLIGATION, DUTY, OR LIABILITY WHATSOEVER IN CONTRACT, TORT (INCLUDING BUT NOT LIMITED TO NEGLIGENCE) OR OTHERWISE TO USER. THE LIMITATIONS, EXCLUSIONS AND DISCLAIMERS IN THIS AGREEMENT SHALL APPLY IRRESPECTIVE OF THE NATURE OF THE CAUSE OF ACTION, DEMAND, OR ACTION BY USER, INCLUDING BREACH OF CONTRACT, NEGLIGENCE, TORT, OR ANY OTHER LEGAL THEORY AND SHALL SURVIVE A FUNDAMENTAL BREACH OR BREACHES OR THE FAILURE OF THE ESSENTIAL PURPOSE OF THIS AGREEMENT OR OF ANY REMEDY CONTAINED HEREIN. SOME STATES AND JURISDICTIONS DO NOT ALLOW LIMITATIONS ON DURATION OR THE EXCLUSION OF AN IMPLIED WARRANTY, OR MAY PROVIDE ADDITIONAL RIGHTS THAT MAY NOT BE WAIVED PURSUANT TO THIS DOCUMENT.<br><br>
				d. YOU HEREBY ACKNOWLEDGE THAT WE ARE NOT RESPONSIBLE FOR ANY INTERCEPTED INFORMATION SENT VIA THE INTERNET, AND YOU HEREBY RELEASE US FROM ANY AND ALL CLAIMS ARISING OUT OF OR RELATED TO THE USE OF INTERCEPTED INFORMATION IN ANY UNAUTHORIZED MANNER.<br><br>
				e. USERS WHO RESIDE IN CALIFORNIA AGREE TO WAIVE CALIFORNIA CIVIL CODE SECTION 1542, WHICH STATES "A GENERAL RELEASE DOES NOT EXTEND TO CLAIMS WHICH THE CREDITOR DOES NOT KNOW OR SUSPECT TO EXIST IN HIS OR HER FAVOR AT THE TIME OF EXECUTING THE RELEASE, WHICH IF KNOWN BY HIM OR HER MUST HAVE MATERIALLY AFFECTED HIS OR HER SETTLEMENT WITH THE DEBTOR."<br><br>
				f. TO THE FULLEST EXTENT POSSIBLE BY LAW, OUR MAXIMUM LIABILITY ARISING OUT OF OR IN CONNECTION WITH THE SITE OR YOUR USE OF OUR CONTENT, REGARDLESS OF THE CAUSE OF ACTION (WHETHER IN CONTRACT, TORT, BREACH OF WARRANTY OR OTHERWISE), WILL NOT EXCEED ONE-HUNDRED DOLLARS ($100.00).<br><br>
				20. INDEMNIFICATION<br>
				You agree to indemnify and hold us, our affiliates, employees, officers, directors and shareholders (each an "Indemnitee") harmless from and against any claims, suits, actions or proceedings ("Claims") brought and damages, costs (including attorneys' fees) and/or judgments awarded against us that arise from or in connection with: (i) Claims by any person or entity to the extent that such Claims are based upon or arise out of user's use of the Site or user's actions, (ii) breach by user of this Agreement, or (iii) user's failure to comply with all applicable laws. We shall give user written notice of such Claims, permit user to defend (with counsel reasonably acceptable to us) and/or settle such Claims (upon terms reasonably acceptable to us), and, subject to our sole discretion, give user information and assistance reasonably requested by user in connection with such Claims.<br><br>
				21. AS IS, WITH ALL FAULTS<br>
				The Site is provided on an "AS IS" and "WITH ALL FAULTS" basis.<br><br>
				22. SURVIVAL<br>
				The provisions of this Agreement that by their nature are intended to survive the expiration or earlier termination, including those provisions relating to ownership, indemnification/defense, warranty disclaimer, and limits of liability shall survive the expiration or earlier termination of this Agreement.<br><br>
				23. MISCELLANEOUS<br>
				a. <em>Notice</em>. We may give notice by means of a general notice through the Site. You may give notice to us at any time by any sending an email with confirmed receipt to <a href="mailto:legal@expertsolarhelp.com">legal@expertsolarhelp.com</a>, or by letter which is delivered by nationally recognized overnight delivery service to the following address: ATTN: ExpertSolarHelp.com, C/O C2C Marketing Inc., 2657 Windmill Pkwy, Suite 265, Henderson, NV 89074.<br><br>
				b. <em>Force Majeure</em>. If the performance of this Agreement, or any obligation hereunder is prevented, restricted, or interfered with by reason of fire, flood, earthquake, explosion or other casualty or accident or act of God, strikes or labor disputes, inability to procure or obtain delivery of items, supplies, telecommunication services, equipment or software, war or other violence, any law, order, proclamation, regulation, ordinance, demand or requirement of any governmental authority, or any other act or condition whatsoever beyond our reasonable control, we shall be excused from such performance to the extent of such prevention.<br><br>
				c. <em>Severability</em>. To the extent that any provision or portion of this Agreement is deemed to be invalid, illegal or unenforceable, such provision or portion shall be severed and deleted or limited so as to give effect to the intent of the parties insofar as possible and the remainder of this Agreement, as the case may be, shall remain binding upon the parties.<br><br>
				d. <em>Assignment</em>. User may not, without our prior written consent (which may be given or withheld in our sole discretion), assign or transfer this Agreement or any of its rights or obligations under this Agreement to any third-person. We may assign this Agreement to any person or entity without your consent. We may delegate to our affiliates, agents, suppliers and contractors any of the obligations herein imposed upon us and we may disclose to any such persons any information required by them to perform the duties so delegated to them.<br><br>
				e. <em>Waiver</em>. A failure or delay by us to enforce any right under this Agreement shall not at any time constitute a waiver of such right or any other right, and shall not modify the rights or obligations of either party under this Agreement.<br><br>
				f. <em>Governing Law</em>. This Agreement shall be governed by and construed in accordance with the laws of the State of Nevada without reference to conflict or choice of law rules or principles.<br><br>
				g. <em>Arbitration</em>. ANY DISPUTE, CONTROVERSY OR CLAIM ARISING OUT OF, RELATING TO OR IN CONNECTION WITH THIS AGREEMENT, INCLUDING THE BREACH, TERMINATION OR VALIDITY THEREOF, SHALL BE FINALLY RESOLVED BY ARBITRATION OR SMALL CLAIMS COURT. The arbitration tribunal shall have the power to rule on any challenge to its own jurisdiction or to the validity or enforceability of any portion of the agreement to arbitrate. THE PARTIES AGREE TO ARBITRATE SOLELY ON AN INDIVIDUAL BASIS, AND THAT THIS AGREEMENT DOES NOT PERMIT CLASS ARBITRATION OR ANY CLAIMS BROUGHT AS A PLAINTIFF OR CLASS MEMBER IN ANY CLASS OR REPRESENTATIVE ARBITRATION PROCEEDING. The arbitration may take place in the consumer's home county and may be conducted by phone at consumer's election. We will cover the costs of arbitration. The arbitral tribunal may not consolidate more than one person's claims, and may not otherwise preside over any form of a representative or class proceeding. In the event the prohibition on class arbitration is deemed invalid or unenforceable, then the remaining portions of the arbitration agreement will remain in force, except in the event that class arbitration is requested, in which case the entire agreement to arbitrate will be null and void.<br><br>
				h. <em>Non-Arbitration Forum; Venue</em>. In the event that a challenge to the jurisdiction of the arbitrator or a challenge to the validity or enforceability of any portion of the agreement to arbitrate is sustained, the parties irrevocably and unconditionally submit to the exclusive jurisdiction of the courts of the State of Nevada located in Clark County or in the United States District Court for the District of Nevada for the purposes of any suit, action or other proceeding arising out of this Agreement or the subject matter hereof brought by any party hereto; and hereby waive and agree not to assert as a defense or otherwise, in any such suit, action or proceeding, any claim that it is not subject personally to the jurisdiction of the above-named courts, that the suit, action or proceeding is brought in an inconvenient forum, or that the venue of the suit, action or proceeding is improper.<br><br>
				i. <em>Waiver of Jury Trial and Class Suit</em>. You acknowledge and understand that, with respect to any dispute with us, our affiliates, employees, officers, directors and members relating to or arising from your use of the Site or this Agreement that YOU ARE GIVING UP YOUR RIGHT TO HAVE A TRIAL BY JURY AND YOU ARE GIVING UP YOUR RIGHT TO SERVE AS A REPRESENTATIVE, AS A PRIVATE ATTORNEY GENERAL, OR IN ANY OTHER REPRESENTATIVE CAPACITY, OR TO PARTICIPATE AS A MEMBER OF A CLASS OF CLAIMANTS, IN ANY LAWSUIT INVOLVING SUCH DISPUTE.<br><br>
				j. <em>Miscellaneous</em>. All covenants, agreements, representations and warranties made in this Agreement shall survive your acceptance of this Agreement and the termination of this Agreement.<br><br>
				k. <em>Construction</em>. The titles of the sections of this Agreement are for convenience of reference only and are not to be considered in construing any meanings contained in this Agreement. Unless the context of this Agreement clearly requires otherwise: (i) references to the plural include the singular, the singular the plural, and the part the whole, (ii) references to one gender include all genders, (iii) "or" has the inclusive meaning frequently identified with the phrase "and/or," (iv) "including" has the inclusive meaning frequently identified with the phrase "including but not limited to" or "including without limitation," and (v) references to "hereunder," "herein" or "hereof" relate to this Agreement as a whole. Any reference in this Agreement to any statute, rule, regulation or agreement, including this Agreement, shall be deemed to include such statute, rule, regulation or agreement as it may be modified, varied, amended or supplemented from time to time. The parties agree that this Agreement shall be fairly interpreted in accordance with its terms without any strict construction in favor of or against either party, and that ambiguities shall not be interpreted against the drafting party.<br><br>
				l. <em>Attorneys' Fees</em>. If a challenge to the jurisdiction of the arbitrator or a challenge to the validity or enforceability of any portion of the agreement to arbitrate is sustained and a lawsuit between you and us is necessary in order to enforce any of the terms of this Agreement, the prevailing party in any such action shall be entitled to recover its reasonable attorneys' fees and costs from the non-prevailing party.<br><br>
				m. <em>Relationship</em>. This Agreement creates no agency, partnership, joint venture, or employee-employer relationship between you and us, unless otherwise stated in writing by us.<br><br>
				n. <em>Entire Agreement</em>. This Agreement sets forth the entire agreement of the parties, and supersedes any prior agreement and any prior discussion between the parties, relating to the subject matter contained herein. Neither party shall be bound by any definition, condition, provision, representation, warranty, covenant or promise other than as expressly stated in this Agreement or as contemporaneously or subsequently set forth in writing and signed by a duly authorized officer or representative of the party to be bound thereby.<br><br>
				24. CONTACT US<br>
				Any comments or requests for further information may be directed to:<br><br>
				ATTN: ExpertSolarHelp.com<br>
				C/O C2C Marketing Inc.<br>
				2657 Windmill Pkwy<br>
				Suite 265<br>
				Henderson, NV 89074<br>
